public with sharing class CampingListController {
    // STERN LECTURE ABOUT WHAT'S MISSING HERE COMING SOON 
    @AuraEnabled 
    public static List<Camping_Item__c> getItems() {
        // Check to make sure all fields are accessible to this user
        String[] fieldsToCheck = new String[] {
            'Id', 'Name', 'Price__c', 'Quantity__c', 'Packed__c' ,'CreatedDate'
        };
        Map<String,Schema.SObjectField> fieldDescribeTokens =
            Schema.SObjectType.Camping_Item__c.fields.getMap();
        for(String field : fieldsToCheck) {
            if( ! fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
            }
        }
        // OK, they're cool, let 'em through
        return [SELECT  Id, Name, Price__c, Quantity__c,Packed__c ,CreatedDate
                FROM Camping_Item__c];
    }
    @AuraEnabled
    public static Camping_Item__c saveItem(Camping_Item__c camping) {
        // Perform isUpdateable() checking first, then
        upsert camping;
        return camping;
    } 
}